update workflows

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -1,9 +1,15 @@
-name: Freqtrade Hyperopt Matrix
+name: Freqtrade Matrix Jobs
+run-name: "Freqtrade Matrix: ${{ inputs.RUN_MODE }} (${{ vars.SCORE }})"
 
 on:
   workflow_dispatch:
     inputs:
-      matrix_json:
+      RUN_MODE:
+        description: 'Custom run name'
+        default: 'Hyperopt'
+        required: false
+        type: string
+      MATRIX_JSON:
         description: "Matrix JSON (as string)"
         required: true
 
@@ -20,16 +26,18 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        hyperopts: ${{ fromJson(inputs.matrix_json).hyperopts }}
+        FIELDS: ${{ fromJson(inputs.MATRIX_JSON).fields }}
 
     env:
+      SCORE: ${{ vars.SCORE }}
+      RUN_MODE: ${{ inputs.RUN_MODE }}
       GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
       RUNNER_TITLE: "Google-optimized-instance"
       TARGET_REPOSITORY: ${{ vars.TARGET_REPOSITORY }}
 
     steps:
       - name: 📥 Checkout Repo
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
 
       - name: ⚙️ Build Maps
         uses: eq19/maps@v8
@@ -50,42 +58,57 @@ jobs:
 
       - name: 🪂 Install freqtrade
         shell: bash
+        env:
+          VERSION: "2025.12"
         run: |
           cd user_data/build_helpers
           ./install_ta-lib.sh > /dev/null 2>&1 && rm -rf *.txt
 
           # Download requirement files from Freqtrade 2025.10 (corrected)
-          curl -s https://api.github.com/repos/freqtrade/freqtrade/contents?ref=2025.10 \
-            | jq -r '.[] | select(.name | test("^requirements(-.*)?\\.txt$")) | .path' \
-            | xargs -I{} curl -sO "https://raw.githubusercontent.com/freqtrade/freqtrade/2025.10/{}"
+          for f in requirements.txt requirements-dev.txt requirements-hyperopt.txt requirements-plot.txt requirements-freqai.txt requirements-freqai-rl.txt; do
+            curl -fsSLO --retry 5 --retry-delay 2 \
+            https://raw.githubusercontent.com/freqtrade/freqtrade/$VERSION/$f || true
+          done          
 
           pip install -qq --no-cache-dir -r ${{ github.workspace }}/user_data/build_helpers/requirements-plot.txt
           pip install -qq --no-cache-dir -r ${{ github.workspace }}/user_data/build_helpers/requirements-hyperopt.txt
-          pip install -qq --no-cache-dir -r ${{ github.workspace }}/user_data/build_helpers/requirements-freqai-rl.txt
+          [[ "$RUN_MODE" == "FreqAI" ]] && pip install -qq --no-cache-dir -r ${{ github.workspace }}/user_data/build_helpers/requirements-freqai-rl.txt
 
           #pip install -qq --no-cache-dir --no-build-isolation --upgrade freqtrade
-          pip install -qq --no-cache-dir ta "numpy<3.0" "aiodns<3.0" "freqtrade==2025.10"
+          pip install -qq --no-cache-dir ta "numpy<3.0" "aiodns<3.0" "freqtrade==$VERSION"
 
       - name: ⚙️ Get artifact ID
         id: get-artifact-id
-        uses: actions/github-script@v7
+        uses: actions/github-script@v8
         with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
-            const matrix = JSON.parse(context.payload.inputs.matrix_json);
+            const matrix = JSON.parse(context.payload.inputs.MATRIX_JSON);
             const artifactName = 'freqtrade-data';
             const runId = matrix.run_id;
 
-            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              run_id: runId,
-            });
+            for (let i = 0; i < 20; i++) {
+              try {
+                const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
+                  owner: context.repo.owner,
+                  repo: context.repo.repo,
+                  run_id: runId,
+                });
 
-            const match = artifacts.data.artifacts.find(a => a.name === artifactName);
-            if (!match) {
-              throw new Error(`Artifact '${artifactName}' not found in run ${runId}`);
+                const match = artifacts.data.artifacts.find(a => a.name === artifactName);
+
+                if (match) {
+                  core.setOutput('artifact_id', match.id);
+                  return;
+                }
+
+              } catch (e) {
+                console.log(`Attempt ${i + 1} failed: ${e.message}`);
+                await new Promise(r => setTimeout(r, 2000));
+              }
             }
-            core.setOutput('artifact_id', match.id);
+
+            throw new Error("Artifact lookup failed after retries");
 
       - name: Download artifact zip using curl
         run: |
@@ -101,16 +124,14 @@ jobs:
       - name: Show contents
         run: ls -R user_data/data
 
-      - name: 🧠 Run Hyperopt
+      - name: 🧠 Run Script
         timeout-minutes: 360
         env:
-          HYPEROPT: ${{ matrix.hyperopts }}
-          SPACE: ${{ fromJson(inputs.matrix_json).space }}
-          SCORE: ${{ fromJson(inputs.matrix_json).score }}
-          FREQAI_MODEL: ${{ fromJson(inputs.matrix_json).freqai }}
-          REDUCE_EPOCH: ${{ fromJson(inputs.matrix_json).reduce_epoch }}
+          MATRIX_INPUT: ${{ matrix.FIELDS }}
+          ID: ${{ fromJson(inputs.MATRIX_JSON).repo_id }}
+          REDUCE_EPOCH: ${{ fromJson(inputs.MATRIX_JSON).reduce_epoch }}
         run: |
-          echo "Running hyperopt..."
           echo "Score: $SCORE"
+          echo "Running $RUN_MODE..."
           echo "Reduce epoch: $REDUCE_EPOCH"
-          bash user_data/ft_client/test_client/feed.sh hyperopt
+          bash user_data/ft_client/test_client/feed.sh $RUN_MODE
